"""
ConfTest Interactive Web Dashboard & REST API.

FastAPI backend with a built-in dashboard for live project demonstrations,
reliability reporting, health checks, and Pull Request selection inspection.

Every number on the page is read from a report artifact at request time. The four
stat cards used to be literals in the HTML -- 45.2% time reduction, 99.4% failure
recall, ECE 0.028 "68% error reduction", and $4,880 monthly ROI -- none of which
came from a run, and all four of which the repository's own
reports/baseline_comparison.csv contradicts (58.8%, 40.0%, 3 escaped commits).
The table heading also credited "Defects4J / OSS Repos", a corpus this project has
never evaluated on, and the loading text announced a 450-commit benchmark while
the runner behind it was constructed for 350.

The benchmark endpoint now serves the measured CSV. It previously re-ran
ExperimentRunner, which has raised ValueError on every call since the synthetic
dataset generator started refusing to fabricate labels without
acknowledge_synthetic=True -- so the one honest element of the page was dead
while the fabricated cards above it still rendered.

.. deprecated:: superseded

    NOT AUTHORITATIVE. This module is an earlier implementation kept only so
    that the tests written against it still run. The maintained implementation
    is **conftest.api.main** (the served API; the dashboard UI is dashboard/app.py at the repo root).

    Two trees with the same responsibility is how a repository ends up
    measuring one and shipping the other: fixes land in `src/conftest/` and are
    invisible here, so a number produced by this module can silently disagree
    with the published pipeline. Import the replacement in new code. Nothing
    under `src/conftest/`, `scripts/`, or `dashboard/` imports this module, and
    nothing new should.
"""
__superseded_by__ = "conftest.api.main"


import csv
import sys
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse
import uvicorn

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from conftest.evaluation.headline import (
    BASELINE_CSV,
    MissingArtifact,
    POLICY_CONFIG,
    headline_metrics,
    provenance,
    read_json,
)

app = FastAPI(
    title="ConfTest CI/CD Optimization API",
    description="Confidence-Calibrated Regression Test Selection with Selective Prediction",
    version="1.0.0",
)

BENCHMARK_PRODUCED_BY = "python scripts/train_baseline.py"


def _escape(text: Any) -> str:
    """Minimal HTML escaping: artifact strings reach the page as text, not markup."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


@app.get("/health")
@app.get("/api/health")
def health_check():
    """Health check endpoint for CI/CD and deployment monitoring."""
    return JSONResponse(
        content={"status": "healthy", "service": "ConfTest API", "version": "1.0.0"}
    )


@app.get("/api/benchmark-results")
def get_benchmark():
    """
    The measured benchmark table, or a 503 naming the command that produces it.

    Reads the CSV on every request rather than caching: the file is regenerated by
    a script, and a cached copy would keep serving the previous run's numbers with
    no way for a reader to tell.
    """
    csv_path = PROJECT_ROOT / BASELINE_CSV
    if not csv_path.exists():
        return JSONResponse(
            status_code=503,
            content={
                "error": f"{BASELINE_CSV.as_posix()} has not been produced yet.",
                "produced_by": BENCHMARK_PRODUCED_BY,
                "results": [],
            },
        )
    with csv_path.open(newline="", encoding="utf-8") as handle:
        rows: List[Dict[str, str]] = list(csv.DictReader(handle))
    return JSONResponse(
        content={
            "source": BASELINE_CSV.as_posix(),
            "labels_measured": provenance(PROJECT_ROOT).real_labels,
            "results": rows,
        }
    )


def _cards_html() -> str:
    """
    The stat row, one card per measured headline.

    A headline with no artifact behind it renders as "not measured" with the
    command that would produce it, so an absent measurement cannot be mistaken for
    a poor one.
    """
    cards = []
    for headline in headline_metrics(PROJECT_ROOT):
        value = _escape(headline.value) if headline.measured else "not measured"
        value_class = "value" if headline.measured else "value unmeasured"
        cards.append(
            f'<div class="stat-card">'
            f"<h3>{_escape(headline.label)}</h3>"
            f'<div class="stat-value {value_class}">{value}</div>'
            f'<div class="subtext">{_escape(headline.note)}</div>'
            f'<div class="source">source: <code>{_escape(headline.source)}</code></div>'
            f"</div>"
        )
    return '<div class="stats-grid">' + "".join(cards) + "</div>"


def _provenance_html() -> str:
    """Whether a test suite was ever executed to produce the labels behind the cards."""
    prov = provenance(PROJECT_ROOT)
    css_class = "banner ok" if prov.real_labels else "banner warn"
    prefix = "Labels measured." if prov.real_labels else "Labels not measured."
    return f'<div class="{css_class}"><strong>{prefix}</strong> {_escape(prov.detail)}</div>'


def _policy_card_html() -> str:
    """
    The abstention thresholds the engine actually runs with.

    This panel used to be a mock PR review with invented numbers -- "12 / 50 Tests
    (76.0% Time Saved)", "Confidence: 94.8% (Uncertainty: 0.052 < 0.180)" and three
    SHAP drivers at +0.42 / +0.28 / +0.14. No pull request produced any of it. The
    thresholds below are read from the tuned policy; live per-PR selection is on the
    Streamlit portal's "Live PR Evaluation" page, which runs the engine.
    """
    try:
        policy = read_json(POLICY_CONFIG, "python scripts/tune_policy.py", PROJECT_ROOT)
    except MissingArtifact as exc:
        return (
            '<div class="pr-simulator"><div class="pr-bot-header">Abstention policy</div>'
            f"<p>Not tuned yet: <code>{_escape(exc.path.as_posix())}</code> does not exist.</p>"
            f"<p>Produce it with <code>{_escape(exc.produced_by)}</code>.</p></div>"
        )

    rows = "".join(
        f"<p><strong>{_escape(key)}:</strong> <code>{_escape(value)}</code></p>"
        for key, value in policy.items()
        if not isinstance(value, (dict, list))
    )
    return (
        '<div class="pr-simulator">'
        '<div class="pr-bot-header">Abstention policy in force</div>'
        f"{rows}"
        f'<p class="muted">Read from <code>{_escape(POLICY_CONFIG.as_posix())}</code>. '
        "A commit whose ensemble disagreement exceeds the abstention threshold runs the "
        "full suite instead of a selection.</p>"
        "</div>"
    )


_CSS = """
        :root {
            --primary: #1e40af;
            --primary-light: #3b82f6;
            --bg: #0f172a;
            --card-bg: #1e293b;
            --text: #f8fafc;
            --text-muted: #94a3b8;
            --border: #334155;
            --accent: #06b6d4;
            --success: #10b981;
            --warning: #f59e0b;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Segoe UI', system-ui, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            padding: 24px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid var(--border);
            padding-bottom: 16px;
            margin-bottom: 24px;
        }
        .header h1 { font-size: 20pt; color: #60a5fa; }
        .header p { color: var(--text-muted); font-size: 10pt; }
        .badge {
            background: rgba(16, 185, 129, 0.2);
            color: #34d399;
            border: 1px solid #059669;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 9pt;
            font-weight: 600;
        }
        .banner {
            border-radius: 8px;
            padding: 12px 16px;
            margin-bottom: 20px;
            font-size: 9.5pt;
            line-height: 1.5;
        }
        .banner.ok { background: rgba(16, 185, 129, 0.12); border: 1px solid #059669; }
        .banner.warn { background: rgba(245, 158, 11, 0.12); border: 1px solid #b45309; }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 24px;
        }
        .stat-card {
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 16px;
        }
        .stat-card h3 { font-size: 10pt; color: var(--text-muted); text-transform: uppercase; margin-bottom: 6px; }
        .stat-card .value { font-size: 20pt; font-weight: 700; color: #38bdf8; }
        .stat-card .value.unmeasured { font-size: 13pt; color: var(--warning); }
        .stat-card .subtext { font-size: 8.5pt; color: #10b981; margin-top: 4px; line-height: 1.4; }
        .stat-card .source { font-size: 8pt; color: var(--text-muted); margin-top: 6px; }
        .main-grid {
            display: grid;
            grid-template-columns: 2fr 1fr;
            gap: 20px;
            margin-bottom: 24px;
        }
        .card {
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 20px;
        }
        .card h2 { font-size: 13pt; margin-bottom: 6px; color: #93c5fd; }
        .card .provenance { font-size: 8.5pt; color: var(--text-muted); margin-bottom: 14px; }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9pt;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }
        th { color: var(--text-muted); background: #0f172a; }
        tr:hover { background: #334155; }
        .highlight-row { background: rgba(59, 130, 246, 0.15); font-weight: 600; color: #93c5fd; }
        .pr-simulator {
            background: #0f172a;
            border: 1px solid var(--border);
            border-radius: 6px;
            padding: 14px;
            font-family: Consolas, monospace;
            font-size: 9pt;
            line-height: 1.6;
        }
        .pr-bot-header {
            color: #38bdf8;
            font-weight: 700;
            margin-bottom: 8px;
            border-bottom: 1px dashed var(--border);
            padding-bottom: 6px;
        }
        .pr-simulator .muted { color: var(--text-muted); margin-top: 8px; }
        .btn {
            background: var(--primary-light);
            color: white;
            border: none;
            padding: 8px 16px;
            border-radius: 6px;
            cursor: pointer;
            font-weight: 600;
        }
        .btn:hover { background: var(--primary); }
"""
